# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(428, 366)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_id = QtWidgets.QLabel(self.centralwidget)
        self.label_id.setGeometry(QtCore.QRect(20, 20, 56, 12))
        self.label_id.setObjectName("label_id")
        self.label_pwd = QtWidgets.QLabel(self.centralwidget)
        self.label_pwd.setGeometry(QtCore.QRect(20, 50, 56, 12))
        self.label_pwd.setObjectName("label_pwd")
        self.input_id = QtWidgets.QLineEdit(self.centralwidget)
        self.input_id.setGeometry(QtCore.QRect(80, 20, 251, 20))
        self.input_id.setObjectName("input_id")
        self.input_pwd = QtWidgets.QLineEdit(self.centralwidget)
        self.input_pwd.setGeometry(QtCore.QRect(80, 50, 251, 20))
        self.input_pwd.setObjectName("input_pwd")
        self.input_kw = QtWidgets.QLineEdit(self.centralwidget)
        self.input_kw.setGeometry(QtCore.QRect(80, 80, 91, 20))
        self.input_kw.setObjectName("input_kw")
        self.label_kw = QtWidgets.QLabel(self.centralwidget)
        self.label_kw.setGeometry(QtCore.QRect(20, 80, 56, 12))
        self.label_kw.setObjectName("label_kw")
        self.label_number = QtWidgets.QLabel(self.centralwidget)
        self.label_number.setGeometry(QtCore.QRect(180, 80, 91, 16))
        self.label_number.setObjectName("label_number")
        self.input_number = QtWidgets.QLineEdit(self.centralwidget)
        self.input_number.setGeometry(QtCore.QRect(270, 80, 61, 20))
        self.input_number.setObjectName("input_number")
        self.btn_start = QtWidgets.QPushButton(self.centralwidget)
        self.btn_start.setGeometry(QtCore.QRect(340, 22, 71, 81))
        self.btn_start.setObjectName("btn_start")
        self.tb_log = QtWidgets.QTextBrowser(self.centralwidget)
        self.tb_log.setGeometry(QtCore.QRect(10, 110, 401, 221))
        self.tb_log.setObjectName("tb_log")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 428, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_id.setText(_translate("MainWindow", "아이디"))
        self.label_pwd.setText(_translate("MainWindow", "비밀번호"))
        self.label_kw.setText(_translate("MainWindow", "키워드"))
        self.label_number.setText(_translate("MainWindow", "추출 데이터 수"))
        self.btn_start.setText(_translate("MainWindow", "시작"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
