# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(951, 552)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.input_id = QtWidgets.QLineEdit(self.centralwidget)
        self.input_id.setGeometry(QtCore.QRect(120, 40, 291, 30))
        self.input_id.setObjectName("input_id")
        self.label_kw = QtWidgets.QLabel(self.centralwidget)
        self.label_kw.setGeometry(QtCore.QRect(450, 40, 56, 30))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(11)
        self.label_kw.setFont(font)
        self.label_kw.setObjectName("label_kw")
        self.btn_start = QtWidgets.QPushButton(self.centralwidget)
        self.btn_start.setGeometry(QtCore.QRect(800, 40, 101, 70))
        self.btn_start.setObjectName("btn_start")
        self.tb_log = QtWidgets.QTextBrowser(self.centralwidget)
        self.tb_log.setGeometry(QtCore.QRect(40, 190, 870, 321))
        self.tb_log.setObjectName("tb_log")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 170, 231, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(610, 160, 300, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.input_pwd = QtWidgets.QLineEdit(self.centralwidget)
        self.input_pwd.setGeometry(QtCore.QRect(120, 90, 291, 30))
        self.input_pwd.setObjectName("input_pwd")
        self.input_kw = QtWidgets.QLineEdit(self.centralwidget)
        self.input_kw.setGeometry(QtCore.QRect(580, 40, 171, 30))
        self.input_kw.setObjectName("input_kw")
        self.input_num = QtWidgets.QLineEdit(self.centralwidget)
        self.input_num.setGeometry(QtCore.QRect(580, 90, 171, 30))
        self.input_num.setObjectName("input_num")
        self.label_kw_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_kw_2.setGeometry(QtCore.QRect(450, 90, 130, 30))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(11)
        self.label_kw_2.setFont(font)
        self.label_kw_2.setObjectName("label_kw_2")
        self.label_kw_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_kw_3.setGeometry(QtCore.QRect(40, 40, 56, 30))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(11)
        self.label_kw_3.setFont(font)
        self.label_kw_3.setObjectName("label_kw_3")
        self.label_kw_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_kw_4.setGeometry(QtCore.QRect(40, 90, 60, 30))
        font = QtGui.QFont()
        font.setFamily("맑은 고딕")
        font.setPointSize(11)
        self.label_kw_4.setFont(font)
        self.label_kw_4.setObjectName("label_kw_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 951, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_kw.setText(_translate("MainWindow", "키워드"))
        self.btn_start.setText(_translate("MainWindow", "시작"))
        self.label.setText(_translate("MainWindow", "출력 로그"))
        self.label_kw_2.setText(_translate("MainWindow", "추출할 데이터 수"))
        self.label_kw_3.setText(_translate("MainWindow", "아이디"))
        self.label_kw_4.setText(_translate("MainWindow", "비밀번호"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
